kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k3s-node-termination-handler
subjects:
- kind: ServiceAccount
  name: k3s-node-termination-handler
roleRef:
  kind: Role
  name: k3s-node-termination-handler
  apiGroup: rbac.authorization.k8s.io
